<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>bin\Release\</OutputPath>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <PropertyGroup>
    <KSPDIR Condition="'$(KSPDIR)' == ''">$(Environment_KSPDIR)</KSPDIR>
    <KSPDIR Condition="'$(KSPDIR)' == '' And Exists('C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program')">C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program</KSPDIR>
    <KSPDIR Condition="'$(KSPDIR)' == '' And Exists('C:\Kerbal Space Program')">C:\Kerbal Space Program</KSPDIR>
    <KSPDIR Condition="'$(KSPDIR)' == ''">$(ProjectDir)\libs</KSPDIR>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="src\CoreKinetics\**\*.cs" />
    <Compile Include="src\Configuration\KortexSettings.cs" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net472" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>$(ProjectDir)\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Assembly-CSharp">
      <HintPath Condition="Exists('$(KSPDIR)\KSP_x64_Data')">$(KSPDIR)\KSP_x64_Data\Managed\Assembly-CSharp.dll</HintPath>
      <HintPath Condition="!Exists('$(KSPDIR)\KSP_x64_Data')">$(KSPDIR)\KSP_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath Condition="Exists('$(KSPDIR)\KSP_x64_Data')">$(KSPDIR)\KSP_x64_Data\Managed\Assembly-CSharp-firstpass.dll</HintPath>
      <HintPath Condition="!Exists('$(KSPDIR)\KSP_x64_Data')">$(KSPDIR)\KSP_Data\Managed\Assembly-CSharp-firstpass.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine">
      <HintPath Condition="Exists('$(KSPDIR)\KSP_x64_Data')">$(KSPDIR)\KSP_x64_Data\Managed\UnityEngine.dll</HintPath>
      <HintPath Condition="!Exists('$(KSPDIR)\KSP_x64_Data')">$(KSPDIR)\KSP_Data\Managed\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath Condition="Exists('$(KSPDIR)\KSP_x64_Data')">$(KSPDIR)\KSP_x64_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      <HintPath Condition="!Exists('$(KSPDIR)\KSP_x64_Data')">$(KSPDIR)\KSP_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>